### ISSUE TITLE
Add the possibility to include a default/preset profile

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#391]
Add the possibility for the game dev to ship a predefined user profile that applies on the first load. 
This allows including inactive example mods that the player can activate if desired.

## Todos

- [x] Add `custom_default_profile` to `ModLoaderOptionsProfile`
- [x]  Add `custom_default_profile` to `ModLoaderStore.ml_options`
- [x] Add check for `custom_default_profile` in `ModLoaderUserProfile._load()`
- [ ] Add `@export` for `ModUserProfile`
   - [ ] Subclass for `mod_list` (exporting the Dictionary is not ideal)

**Comment by KANAjetzt** [comment]
Change of plans. Defining a preset user profile is a pain, so I changed the way the `disabled_mods` setting works to still load the mod into `mod_data`. This way, the metadata is accessible for mod menus.
- #394
