### ISSUE TITLE
Wiki Content Todo (Mod Developers)

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#58]
List of things that need to be added to the wiki. To prevent this issue becoming infinitely expanded, this issue focuses solely on adding docs for **mod developers**.

- [x] Using zipped mods in the editor stops mods from `res://mods-unpacked` from working
- [x] godot.log / mods.log
- [x] Adding child nodes to `ModLoader.{mod_id}` - [eg](https://github.com/BrotatoMods/Brotato-ContentLoader/blob/0f0fd9fbfcb1f6c70423f0e08844fec50fd3df5d/root/mods-unpacked/Darkly77-ContentLoader/mod_main.gd#L41)
- [x] Using child nodes - [eg](https://github.com/BrotatoMods/Brotato-Invasion-Mod/blob/main/root/mods-unpacked/Darkly77-Invasion/ModMain.gd#L23)
- [x] Decompiling games - [eg](https://github.com/GodotModding/godot-mod-loader/wiki/@TEMP:-PR33#development-setup)
- [x] GodotSteam - [eg](https://brotato.wiki.spellsandguns.com/Modding_Notes#Steam_Errors)

Any other suggestions please keep 'em brief so I can just add them to this list 🤗

**Comment by ithinkandicode** [comment]
Closing as all tasks are now done.
